apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ga3 
  janus-idp.io/tekton: ga3
  backstage.io/kubernetes-id: ga3
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ga3
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  