apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ga3-gitops
  description: This is GitOps manifest for ga3   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ga3
    backstage.io/kubernetes-id: ga3 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: northdepot/ga3-gitops 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ga3
