apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ga3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ga3 
  name: ga3
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ga3 
